name: Reuse-build

on:
  workflow_dispatch:

jobs:
  Prepare-env:
    runs-on: ubuntu-latest
    steps:
       - name: print
         run: echo "${{ vars.BTP_SUBACCOUNT }}"
       - name: init
         run: echo "RELEASE_CYCLE=${{ vars.BTP_SUBACCOUNT }}" >> $GITHUB_OUTPUT
    outputs:
      RELEASE_CYCLE: ${{ steps.init.outputs.RELEASE_CYCLE }}
  test-output:
    runs-on: ubuntu-latest
    needs: [Prepare-env]
    steps:
       - name: print
         run: echo "${{ needs.Prepare-env.RELEASE_CYCLE }}"
  Build:
    uses: kdemonie/actions-sandbox/.github/workflows/build.yml@v1
    needs: [Prepare-env]
    with:
      RELEASE_CYCLE: ${{ needs.Prepare-env.RELEASE_CYCLE }}
      ENVIRONMENT: "STAGING"
    secrets:
      inherit
  
