name: Reuse-build

on:
  workflow_dispatch:

jobs:
  Build:
    uses: kdemonie/actions-sandbox/.github/workflows/build.yml@v1
    with:
      RELEASE_CYCLE: ${{ vars.RELEASE }}
      ENVIRONMENT: "STAGING"
    secrets:
      inherit
  
