name: Reuse-build

on:
  workflow_dispatch:

jobs:
  Prepare-env:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
       - name: print
         run: echo "${{ vars.BTP_SUBACCOUNT }}"
    outputs:
      RELEASE_CYCLE: ${{ vars.BTP_SUBACCOUNT }}
  test-output:
    runs-on: ubuntu-latest
    needs: [Prepare-env]
    steps:
       - name: print
         run: echo "${{ needs.Prepare-env.outputs.RELEASE_CYCLE }}"
  Build:
    uses: kdemonie/actions-sandbox/.github/workflows/build.yml@v1
    needs: [Prepare-env]
    with:
      RELEASE_CYCLE: ${{ needs.Prepare-env.outputs.RELEASE_CYCLE }}
      ENVIRONMENT: "STAGING"
    secrets:
      inherit
  
