name: Reuse-build

on:
  workflow_dispatch:
    inputs:
      release_cycle:
        description: 'Enter the release cycle'
        required: true
        default: '25MR1'

jobs:
  Build:
    uses: kdemonie/actions-sandbox/.github/workflows/build.yml@v1
    with:
      RELEASE_CYCLE: ${{vars.ENV_VAR}}
      ENVIRONMENT: "STAGING"
    secrets:
      inherit
  
